### ISSUE TITLE
Instalador com erro na instalação do idioma e moeda

### ISSUE THREAD

**Issue by openbrasil** [opencartbrasil/traducao#24]
olá, estive testando a instalação da tradução na versão 2.0.3.1 do opencart e percebi um problema, o arquivo install.php não esta criando a linguagem e a moeda, comisso da erro no instalador e depois aparece um erro dizendo que a variável pt-br não esta definida no index.php

e na loja ao mudar para pt-br desaparece todo o conteudo...

**Comment by notridan** [comment]
Mesmo problema aqui.

**Comment by ManoelVidal** [comment]
Conseguiram instalar?
