### ISSUE TITLE
Erro na tradução oc 2.2.2

### ISSUE THREAD

**Issue by marabesi** [opencartbrasil/traducao#26]
Estou tentando traduzir o oc 2.2.2 mas ao efetuar a instalação do pacote a home page da loja (não o admin, a loja mesmo) fica tudo em branco. O que notei é que até no admin na listagem dos produtos os registros somem.

Os passos que eu realizei foram :

1) Instalar a tradução através do método sem FTP
2) Ir nas configurações e trocar o idioma da loja para PT-BR

Pra facilitar eu anexei um print também da loja em branco

<img width="1229" alt="screen shot 2016-07-27 at 10 20 38 pm" src="https://cloud.githubusercontent.com/assets/2129872/17198041/67f32f50-5448-11e6-99e6-f47faae1ef56.png">

E a área de administração também, notem que na paginação os registros são contados corretamente

<img width="1265" alt="screen shot 2016-07-27 at 10 22 19 pm" src="https://cloud.githubusercontent.com/assets/2129872/17198080/af007484-5448-11e6-8744-68884f2db984.png">

**Comment by ManoelVidal** [comment]
Está tradução não é compatível com a versão 2.2.2 do OpenCart, que era uma versão de desenvolvimento, ou seja, não deve ser utilizada em produção.
