### ISSUE TITLE
Tradução apaga todos os produtos

### ISSUE THREAD

**Issue by sistematico** [opencartbrasil/traducao#27]
A tradução funciona, porem apaga todos os produtos, categorias, etc...
Testei com uma instalação limpa, Nginx + PHP-FPM em uma vps com o Debian 8 64 bits.

**Comment by davidchc** [comment]
@sistematico Acontece que como é executado install.sql, ele defini pt-br na configuração, na hora de executar o install.php, que adiciona o código o idioma, que copia os textos dos produtos para o idioma criado, ele não encontrava porque busca pelo português, ele ainda não tinha sido criado.

Uma solução, é adicionar no arquivo install.php, antes de:

`$this->model_localisation_language->addLanguage($oc_language);
`

O código:
 
`$this->config->set('config_language_id', 1);
`

Dessa forma ele copiará os produtos, e outras informações e adicionará com idioma pt-br
`

**Comment by ManoelVidal** [comment]
#28
